export const tags = {
  CONST_TAG_NEW: 'NEW',
  CONST_TAG_BEST: 'BEST',
  CONST_TAG_LIVING: 'LIVING',
  CONST_TAG_KITCHEN: 'KITCHEN',
  CONST_TAG_STATIONERY: 'STATIONERY',
  CONST_TAG_BABYKIDS: 'BABY/KIDS'
}
